#!/usr/bin/env sh
### ================================================================
### Shell Install Script
### Detects OS and shell, then sources the correct files.
### ================================================================

SHELL_REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
SHELL_NAME="$(basename "$SHELL")"

echo "=== Shell Installer ==="
echo "Detected repo: ${SHELL_REPO_DIR}"

### --------------------------------
### Detect OS
### --------------------------------
OS="unknown"
case "$(uname -s)" in
	Linux*)   OS="linux" ;;
	FreeBSD*) OS="freebsd" ;;
	MINGW*|CYGWIN*|MSYS*) OS="windows" ;;
esac

echo "Detected OS:    ${OS}"
echo "Detected shell: ${SHELL_NAME}"

### --------------------------------
### Validate
### --------------------------------
PROMPT_FILE="${SHELL_REPO_DIR}/os/${OS}/${SHELL_NAME}/prompt.sh"
if [ ! -f "${PROMPT_FILE}" ]; then
	echo "ERROR: No prompt file found at: ${PROMPT_FILE}"
	echo "Available configs:"
	ls -R "${SHELL_REPO_DIR}/os/" 2>/dev/null
	exit 1
fi

echo "Found prompt:   ${PROMPT_FILE}"
echo ""

### --------------------------------
### Source lines to inject
### --------------------------------
SOURCE_LINE="source \"${PROMPT_FILE}\""
CORE_ENV_LINE="source \"${SHELL_REPO_DIR}/core/environment.sh\""
CORE_FUNC_LINE="source \"${SHELL_REPO_DIR}/core/functions.sh\""

### --------------------------------
### Determine RC file
### --------------------------------
case "${SHELL_NAME}" in
	bash) RC_FILE="${HOME}/.bashrc" ;;
	zsh)  RC_FILE="${HOME}/.zshrc" ;;
	sh)   RC_FILE="${HOME}/.shrc" ;;
	*)    RC_FILE="${HOME}/.${SHELL_NAME}rc" ;;
esac

echo "Target RC file: ${RC_FILE}"
echo ""

### --------------------------------
### Install
### --------------------------------
if grep -qF "${SOURCE_LINE}" "${RC_FILE}" 2>/dev/null; then
	echo "Shell config already installed in ${RC_FILE}"
	echo "Skipping."
else
	echo "=== Shell repo config (auto-generated by install.sh) ===" >> "${RC_FILE}"
	echo "${CORE_ENV_LINE}" >> "${RC_FILE}"
	echo "${CORE_FUNC_LINE}" >> "${RC_FILE}"
	echo "${SOURCE_LINE}" >> "${RC_FILE}"
	echo ""
	echo "Done! Added source lines to ${RC_FILE}"
	echo "Restart your shell or run: source ${RC_FILE}"
fi
